baseurl = "https://gopher.pro.br/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Grupo de Estudos de Golang"
copyright = "© 2020. Grupo de Estudos de Golang. All rights reserved."
author = "Grupo de Estudos de Golang"
paginate = 20
theme = "crg-theme"
enableRobotsTXT = true
description = "Artigos e exemplos de códiog do Grupo de Estudos de Golang"
canonifyurls = true
disableHugoGeneratorInject = true

[taxonomies]
  category = "categorias"
  tag = "tags"

[indexes]
  category = "categorias"
  tag = "tags"
  topic = "topicos"

[params]
  ISO8601 = "2006-01-02T15:04:05JST"
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["go","x86asm"]
  googleAnalytics = "UA-80761879-1"
	locale = "pt-br"
	# Shown in the home page
	subtitle = "programação, eletrônica, golang, UNIX e muito mais papo nerd"
	brand = "Grupode Estudos de Golang"
	dateFormat = "2006-01-02"
    description = "Artigos e posts sobre programação do Grupo de Estudos de Golang"
  [params.publisher]
    name = "Grupo de Estudos de Golang"

    [params.publisher.logo]
      url = "/logo.png"
      width = 600
      height = 60
    
    [params.logo]
      url = "/logo.png"
      width = 600
      height = 60
    
    [params.image]
      url = "/cover.png"
      width = 800
      height = 600


[menu]
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[build]
  publish = "public"
  command = "hugo --minify"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "RSS"]

