baseurl = "https://gopher.pro.br"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Golang grupo de estudos"
copyright = ""
# Shown in the side menu
canonifyurls = true
paginate = 20
theme = "blackburn"
enableRobotsTXT = true
googleAnalytics = "UA-119865485-1"

[params]
	locale = "pt-BR"
	highlight="default"
	# Shown in the home page
	subtitle = "Exemplos, artigos e muito código Go"
	brand = "Gopher Pro"
	# CSS name for highlight.js
	highlightjs = "default"
	dateFormat = "2006-01-02"
	description = "Grupo de estudos de Golang, exemplos, vídeos, aulas, artigos e muito código. Uma comunidade aberta inclusiva e focada na linguagem de programação Go"
	googleAnalytics = "UA-80761879-1"

[indexes]
	category = "categorias"
	tag = "tags"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Sobre"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  #twitter = ""
  #facebook = ""
  #instagram = ""
  #github = ""
  #stackoverflow = "*"
  #linkedin = ""
